
project_id = "kwxaqyxwwmpytiawjgjm"
[functions.generate-linkedin-post]
verify_jwt = true
import_map = "./import_map.json"

[functions.generate-post-image]
verify_jwt = true
import_map = "./import_map.json"

